defaults:
  - _self_

data_preparation:
  center_lat: 45.0
  center_lon: 2.0
  center_depth: 1000.0
  distance: 1000.0
  distance_perc: 0.05
  N: 20000
  duration: 0.5
  f_max: 100.0
  axitra_path: "/home/EU/chmielel/ws/src/signals/Seismic-Angle-Recognition/seismic_angle_recognition/src"
  figures_path: "reports/figures"
  noise_level: 0.02
  output_file: "all_signals.npy"
  output_data_path: "/home/EU/chmielel/ws/src/signals/Seismic-Angle-Recognition/data/signals_2d"
  temp_files_directory: "/home/EU/chmielel/ws/src/signals/Seismic-Angle-Recognition/"

vae_model:
  input_channels: 3  # Assuming 3 dimensions: x,y,z
  input_length: 128 # May vary depending on duration and f_max
  encoder_layers: [16, 32, 64]
  latent_dim: 2  # to have a 2D latent space
  decoder_layers: [64, 32, 16]
  kernel_size: 5
  stride: 2
  padding: 2
  output_padding: 1
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 1000  # Number of epochs for training 
  patience: 3  # Number of epochs with no improvement after which training will be stopped 
  early_stopping_delta: 0.001  # Minimum change to qualify as an improvement  
  train_split: 0.7  # Percentage of data for training 
  val_split: 0.2  # Percentage of data for validation
  data_path: "/home/EU/chmielel/ws/src/signals/Seismic-Angle-Recognition/data/signals_2d/"
  data_filename: "all_signals.npy"
  kl_loss_weight: 0.1  # Weight for the KL loss